# About this script
# ================

# Loads ED bed flow data from get-ED-data-from-Star.R
# Creates charts

# Load libraries
# ==============

library(DBI)
library(dplyr)
library(tidyverse)
library(lubridate)

# Create functions
# ================

# Create summaries for a given time period

calc_node_stats <- function(node_daily, node_daily_seen4hrs, from_date, to_date) {
  
  node_daily <- node_daily %>% 
    filter(date >= from_date, date <= to_date)
  
  node_daily_seen4hrs <- node_daily_seen4hrs %>% 
    filter(date >= from_date, date <= to_date)
  
  node_daily_summ <- node_daily %>% 
    group_by(room7) %>% 
    summarise(num_pat_mean = mean(daily_num_pat),
              num_pat_sd = sd(daily_num_pat),
              duration_mean = mean(daily_duration_mean),
              duration_sd = sd(daily_duration_mean)) %>% 
    # add mean and SD for breach only
    left_join(
      node_daily_seen4hrs %>% 
        filter(seen4hrs == 'Breach') %>% 
        group_by(room7) %>% 
        summarise(num_pat_mean_breach = mean(daily_num_pat),
                  num_pat_sd_beach = sd(daily_num_pat),
                  duration_mean_breach = mean(daily_duration_mean),
                  duration_sd_breach = sd(daily_duration_mean))
    ) %>% 
    # add mean and SD for not breach (seen 4 hours) only
    left_join(
      node_daily_seen4hrs %>% 
        filter(seen4hrs == 'Seen in 4 hours') %>% 
        group_by(room7) %>% 
        summarise(num_pat_mean_seen4hrs = mean(daily_num_pat),
                  num_pat_sd_seen4hrs = sd(daily_num_pat),
                  duration_mean_seen4hrs = mean(daily_duration_mean),
                  duration_sd_seen4hrs = sd(daily_duration_mean))
    )
  return(node_daily_summ)
}



# Load data
# =========

# ED bed move data generated by "get-ED-data-from-Star.R"
load("~/EDcrowding/flow-mapping/data-raw/ED_bed_moves_clean_with_meas_August_2020-08-25.rda")

# load encounter details
load("~/EDcrowding/flow-mapping/data-raw/ED_csn_summ_extra_August_2020-08-06.rda")
ED_csn_summ <- ED_csn_summ_extra

# Create node summaries
# ====================

# note - dates are inclusive
from_date <- "2020-08-01"
to_date <- "2020-08-06"
file_label <- "with_meas_August_"

# First calculate total number and mean duration for each day
node_daily <- ED_bed_moves_with_meas %>% 
  filter(ED_row_excl_OTF ==  1,
         !is.na(room7),
         date(admission) >= date(from_date), 
         date(discharge) <= date(to_date)) %>% 
  mutate(date = date(admission)) %>% 
  group_by(date, room7) %>% 
  summarise(daily_num_pat = n(),
            daily_duration_mean = mean(as.numeric(duration_row, units = "hours")), #this creates daily mean
            daily_duration_sd = sd(as.numeric(duration_row, units = "hours"))) #this creates daily SD

# # Add Admitted and Discharged as nodes
# node_daily <- node_daily %>% dplyr::union(
#   ED_bed_moves_with_meas %>% 
#     filter()
#     left_join(ED_csn_summ %>% select(csn, ED_last_status)) %>% 
#     mutate(date = date(admission)) %>% 
#     group_by(date, ED_last_status) %>% 
#     summarise(daily_num_pat = n(),
#               daily_duration_mean = mean(as.numeric(duration_row, units = "hours")), #this creates daily mean
#               daily_duration_sd = sd(as.numeric(duration_row, units = "hours"))) %>% #this creates daily SD
#     rename(room7 = ED_last_status) 
# )

# Add breach info for each day
node_daily_seen4hrs <- ED_bed_moves_with_meas %>% 
  filter(ED_row_excl_OTF ==  1,
         !is.na(room7),
         date(admission) >= date(from_date), 
         date(discharge) <= date(to_date)) %>% 
  left_join(ED_csn_summ %>% select(csn, seen4hrs)) %>% 
  mutate(date = date(admission)) %>% 
  group_by(date, seen4hrs, room7) %>% 
  summarise(daily_num_pat = n(),
            daily_duration_mean = mean(as.numeric(duration_row, units = "hours")), #this creates daily mean
            daily_duration_sd = sd(as.numeric(duration_row, units = "hours"))) 


# # Add Admitted and Discharged as nodes in the breach info
# node_daily_seen4hrs <- node_daily_seen4hrs %>% dplyr::union(
#   ED_bed_moves_with_meas %>% 
#     left_join(ED_csn_summ %>% select(csn, ED_last_status, seen4hrs)) %>% 
#     mutate(date = date(admission)) %>% 
#     group_by(date, seen4hrs, ED_last_status) %>% 
#     summarise(daily_num_pat = n(),
#               daily_duration_mean = mean(as.numeric(duration_row, units = "hours")), #this creates daily mean
#               daily_duration_sd = sd(as.numeric(duration_row, units = "hours"))) %>% #this creates daily SD
#     rename(room7 = ED_last_status) 
# )

# # Save node stats for future use (note this is a daily list - may not be useful)
# 
# outFile = paste0("EDcrowding/flow-mapping/data-raw/ED_node_daily_",file_label,today(),".rda")
# save(node_daily, file = outFile)
# 
# outFile = paste0("EDcrowding/flow-mapping/data-raw/ED_node_daily_seen4hrs_",file_label,today(),".rda")
# save(node_daily_seen4hrs, file = outFile)

# Create node summaries
# ====================

# Create summaries for a given time period

node_stats <- calc_node_stats(node_daily, node_daily_seen4hrs,
                                   from_date, to_date)  # note - dates are inclusive

outFile = paste0("EDcrowding/flow-mapping/data-output/node_stats_",file_label,today(),".csv")
write.csv(node_stats, file = outFile, row.names = FALSE)


# Create charts
# =============

# chart of mean for each location by day
# note - these charts still use room4 - will need to revisit this

node_daily %>% 
  ggplot(aes(x = date, y = daily_duration_mean)) + geom_bar(stat = "identity") +
  facet_grid(room7 ~.) +
  labs(title = "Mean hours spent in location",
       subtitle = "Source: Star",
       x = "",
       y = "Mean duration (hours)"
  ) +  
  theme_classic()  

# chart of mean over the whole of Jan and Feb

node_daily %>% 
  group_by(room7) %>% 
  summarise(duration_mean = mean(daily_duration_mean)) %>% 
  ggplot(aes(x = room7, y = duration_mean)) + geom_bar(stat = "identity")


# chart of mean for each location by day  - with breach information

node_daily_seen4hrs %>% 
  group_by(room7) %>%   
  ggplot(aes(x = date, y = daily_duration_mean, fill = seen4hrs)) + geom_bar(stat = "identity") +
  facet_grid(room7 ~.) +
  labs(title = "Mean hours spent in location",
       subtitle = "Source: Star",
       x = "",
       y = "Mean duration (hours)",
       fill = "Breach status:"
  ) +  
  theme_classic() +
  theme(legend.position="bottom") 
  


# chart of mean over the whole period - with breach information

node_daily_seen4hrs %>% 
  group_by(room7, seen4hrs) %>% 
  summarise(duration_mean = mean(daily_duration_mean)) %>% 
  ggplot(aes(x = room7, y = duration_mean)) + geom_bar(stat = "identity")


