# About this script
# ================

# Loads ED bed move data generated by get-ED-data-from-Star.R
# Creates an edge list, which contains one row per bed move per patient
# and has a timestamp. 
#
# This patient level data is summarised into a grouped edge list 
# with weights, ready for network analysis. 
#
# In order to decide on the cut point for edge weights, 
# some plots are generated

# Load libraries
# ==============

library(DBI)
library(dplyr)
library(tidyverse)
library(lubridate)


# Define functions
# ================

# define level of granularity for node
# if in ED use room, else use ward name

get_node <- function(dept, room) {
  if (dept == "ED") {
    node <- room
  }
  else {
    node <- dept
  }
}

# for a single encounter, this function generates an edge list of 
# moves between locations, with a timestamp
# locations are provided to it in a tibble called sites
# sites needs 5 attributes: mrn, csn, location, time of admission to location, 
# and time of discharge from location

get_edgelist <- function(sites) {
  
  edgelist <- tribble(
    ~mrn,
    ~csn,
    ~from,
    ~to,
    ~dttm)
  
  from_node = get_node(as.character(sites$dept2[1]), as.character(sites$room3[1]))
  for (j in 1:nrow(sites)) {
    if (j != nrow(sites)) {
      to_node <- get_node(as.character(sites$dept2[j+1]), as.character(sites$room3[j+1]))
      if (from_node != to_node) {
        
        edgelist <- edgelist %>% add_row(tibble_row(
          mrn = sites$mrn[j],
          csn = sites$csn[j],
          from = from_node,
          to = to_node,
          dttm = sites$discharge[j]
        ))
      }
      from_node <- to_node
    }
    else {
      
      edgelist <- edgelist %>% add_row(tibble_row(
        mrn = sites$mrn[j],
        csn = sites$csn[j],
        from = to_node,
        to = "Discharge",
        dttm = sites$discharge_dttm[j]
      ))
      
    }
  }
  return(edgelist)
}


# for  group of encounters, this function generates an edge list of 
# all moves between locations, with a timestamp for each move
# locations are provided to it in a tibble called visits
# visits needs 5 attributes: mrn, csn, location, time of admission to location, 
# time of discharge from location


get_care_site_flows <- function(visits) {

  # filter only those visits with more than one room move
  visits_gt1 <- visits %>% 
    group_by(mrn, csn) %>% 
    summarise("num_visit_details" = n(), "earliest_visit_ts" = min(admission)) %>% 
    filter(num_visit_details > 1)
  
  # then create edge list for all visits
  
  edgedf <- tribble(
    ~mrn,
    ~csn,
    ~from,
    ~to,
    ~dttm)
  
  for (i in (1:nrow(visits_gt1))) {
    
    if (i%%100 == 0) {
      print(paste("Processed",i,"visits"))
    }
    visit_csn = visits_gt1$csn[i]
    num_visits = visits_gt1$num_visit_details[i]
    
    #get all visit detail records for this visit occurence
    sites <- visits %>% filter(csn == visit_csn) %>% arrange(admission)
    
    # create edgelist if the visit involved change of site
    edgelist <- get_edgelist(sites)
    if (nrow(edgelist) > 0) {
      edgedf <- edgedf %>% add_row(edgelist)
    }
  }
  return(edgedf)
}


# function to select only edges with a minimum weight
keep_edges <- function(edgelist_summ, min_weight) {
  # remove minority edges
  keep <- edgelist_summ %>% filter(weight > min_weight)  %>% select(from, to, weight)
  
  # name the edges
  keep <- keep %>% mutate(edge = paste0(from,"~",to)) %>% arrange(from,desc(weight))
}



# Load ED bed move data
# ==================

# generated by get-ED-data-from-Star.R
inFile = paste0("EDcrowding/flow-mapping/data-raw/ED_bed_moves_","2020-06-22",".rda")
load(inFile)

# Create edge list for network graph
# ==================================

# create on edge list which contains one row per bed move per patient with a time stamp
edgedf <- get_care_site_flows(ED_bed_moves %>% 
                                filter(admission_dttm < "2020-03-01") %>% 
                                select(mrn, csn, dept2, room3, admission, admission_dttm, discharge, discharge_dttm))



# save edge list for future use
outFile = paste0("EDcrowding/flow-mapping/data-raw/ED_edge_list_",today(),".rda")
save(edgedf, file = outFile)
rm(outFile)

# OR load edge list if already saved
inFile = paste0("EDcrowding/flow-mapping/data-raw/ED_edge_list_","2020-06-19",".rda")
load(inFile)

# summarise edge list
edgelist_summ <- edgedf %>% group_by(from, to) %>% summarise(weight = n()) %>% arrange(desc(weight))

# look for the right cut point for eliminating edges
ggplot(edgelist_summ, aes(x=1, y = weight)) + 
  geom_boxplot() # wide band at bottom of box plot


ggplot(edgelist_summ %>% filter(weight < 500), aes(x=1, y = weight)) + 
  geom_boxplot() # zooming in suggests 100 is a reasonable cut point


# get reduced edgelist
keep <- keep_edges(edgelist_summ, 100)

# write edgelist to file
outFile <- paste0("EDcrowding/flow-mapping/data-raw/edgelist_summ_gt100",today(),".rda")
save(keep, file = outFile)

outFile <- paste0("EDcrowding/flow-mapping/data-raw/edgelist_summ_gt100",today(),".csv")
write.csv2(keep, file = outFile, row.names = FALSE)



