# About this script
# ================

# Loads ED bed flow data from get-ED-data-from-Star.R
# Creates charts

# Load libraries
# ==============

library(DBI)
library(dplyr)
library(tidyverse)
library(lubridate)

# Load data
# =========

# ED bed move data generated by "get-ED-data-from-Star.R"
inFile = paste0("EDcrowding/flow-mapping/data-raw/ED_bed_moves_","2020-07-09",".rda")
load(inFile)

# Detail for ED CSNs generated by "get-ED-data-from-Star.R"
load("~/EDcrowding/flow-mapping/data-raw/ED_csn_detail_full_2020-07-09.rda")

# Create node list
# ================

# work out csns to ignore if involve pediatrics 
pediatric_csn <- ED_bed_moves %>% group_by(mrn, csn, arrival_dttm) %>% 
  summarise(tot = sum(pediatric_row)) %>% 
  filter(tot > 0) %>% 
  select(mrn, csn) %>% distinct() # 4723

# some csns have rows where the discharge time is earlier than the admission time
odd_csn <- ED_bed_moves %>% filter(discharge < admission) %>% select(csn)
# to see the number of csns removed: 
odd_csn %>% select(csn) %>% n_distinct() #111

# some ED rows have no information about which room someone was in
no_room_csn <-  ED_bed_moves %>% filter(is.na(room4)) %>% select(csn)
# to see the number of csns removed:
no_room_csn %>% select(csn) %>% n_distinct() #8


# this code identifies visits where someone goes to ED from another location

elsewhere_to_ED_csn <- ED_bed_moves %>% 
  group_by(csn) %>% 
  select(csn, ED_row, arrival_row) %>% 
  mutate(check = case_when(ED_row == 1 & !arrival_row & lag(ED_row) == 0 ~ "B",
                          TRUE ~ "A")) %>% 
  filter(check == "B") %>% select(csn)

# identifying those where the first arrival was ED and then they go back there
mult_ED_csn <- ED_bed_moves %>% filter(csn %in% elsewhere_to_ED_csn$csn, arrival_row, ED_row == 1) %>% select(csn)

# for now I will delete these from analysis, but ultimately should accommodate them in my edge list processing etc. 

ED_bed_moves %>% filter(ED_row == 1,
                        !csn %in% elsewhere_to_ED_csn$csn) %>%  
  
  ggplot(aes(x=1, y = as.numeric(ED_duration, units = "days"))) + 
  geom_boxplot() +
  facet_grid(room4 == "OTF"~.)

# plots still showing many long visits

# Continuing to look at long CSNs

long_ED_csn <-  ED_bed_moves %>% filter(!csn %in% elsewhere_to_ED_csn$csn,
                                        as.numeric(ED_duration, units = "days") > 1) %>% select(csn) %>% distinct()


# still 92 csns with more than one day - so repeating the code from above to find out where they get stuck

stuck_in_otf_taf <- ED_bed_moves %>% 
  filter(csn %in% long_ED_csn$csn) %>% 
  select(duration, ED_duration, duration_row, ED_row, admission, discharge, everything())
stuck_in_otf_taf %>% group_by(csn) %>% filter(admission == max(admission)) %>% select(room4) %>% group_by(room4) %>% summarise(tot = n()) %>% arrange(desc(tot))
# lots in OTF and TAF

#stuck_in_otf_taf_csn <- stuck_in_otf_taf %>% group_by(csn) %>% filter(admission == max(admission), room4 %in% c("OTF", "TAF")) %>% select(csn)
stuck_in_otf_taf_csn <- stuck_in_otf_taf %>% group_by(csn) %>% filter(ED_row == 1) %>% filter(admission == max(admission), room4 %in% c("OTF", "TAF")) %>% select(csn)
# Note that doing two separate filters in the above code - picked up 5 more this way

# One is genuinely weird - spent 2 months in ED but only one row
ED_bed_moves %>% filter(csn == "1018734672")

# this one spent 163 in OTF and then went elsewhere in ED so I didn't pick them up
ED_bed_moves %>% filter(csn == "1019997966")

# looking again at the basic ED plot - looks a lot more sensible

ED_bed_moves %>% filter(
    ED_row ==  1,
    date(arrival_dttm) < "2020-03-01",
    date(arrival_dttm) >= "2020-01-01",
    !csn %in% pediatric_csn$csn,
    !csn %in% no_room_csn,    
    !csn %in% odd_csn$csn,
    !csn %in% elsewhere_to_ED_csn$csn,
    !csn %in% stuck_in_otf_taf_csn$csn,
    !csn == "1019997966",  
    !csn == "1018734672") %>% 
  
  ggplot(aes(x=1, y = as.numeric(ED_duration, units = "days"))) + 
  geom_boxplot() +
  facet_grid(room4 == "OTF"~.)

# Calculate node durations

node_duration <- ED_bed_moves %>% 
  filter(
    ED_row ==  1,
    date(arrival_dttm) < "2020-03-01",
    date(arrival_dttm) >= "2020-01-01",
    !csn %in% pediatric_csn$csn,
    !csn %in% no_room_csn,    
    !csn %in% odd_csn$csn,
    !csn %in% elsewhere_to_ED_csn$csn,
    !csn %in% stuck_in_otf_taf_csn$csn,
    !csn == "1019997966",  
    !csn == "1018734672") %>% 
  mutate(date = date(admission)) %>% 
  group_by(date, room4) %>% 
  summarise(daily_duration_mean = mean(as.numeric(duration_row, units = "hours")), #this creates daily mean
            daily_duration_sd = sd(as.numeric(duration_row, units = "hours"))) 

# chart of mean for each location by day (through Jan and Feb)

node_duration %>% 
  ggplot(aes(x = date, y = daily_duration_mean)) + geom_bar(stat = "identity") +
  facet_grid(room4 ~.) 

# chart of mean over the whole of Jan and Feb

node_duration %>% 
  group_by(room4) %>% 
  summarise(duration_mean = mean(daily_duration_mean),
            duration_sd = sd(daily_duration_mean)) %>% # calculating the standard deviation of the mean
  ggplot(aes(x = room4, y = duration_mean)) + geom_bar(stat = "identity")

# Consolidating OTF etc
# ====================

# now adding time in OTF, diagnostics and Waiting room into previous node

# creating new version of ED_bed_moves for now (note this doesn't include non ED rows)
ED_bed_moves_adj <- ED_bed_moves %>% 
  filter(
    ED_row ==  1,
    date(arrival_dttm) < "2020-03-01",
    date(arrival_dttm) >= "2020-01-01",
    !csn %in% pediatric_csn$csn,
    !csn %in% no_room_csn,    
    !csn %in% odd_csn$csn,
    !csn %in% elsewhere_to_ED_csn$csn,
    !csn %in% stuck_in_otf_taf_csn$csn,
    !csn == "1019997966",  
    !csn == "1018734672") %>% 
  select(mrn, csn, arrival_dttm, discharge_dttm, admission, discharge, dept2, room4) %>% 
  group_by(csn) %>%
  # add a column to contain the discharge time of the next row
  mutate(next_location = lead(room4),
                                    next_dttm = lead(discharge)) %>% 
  # use the date for the next row as the discharge time when next row is OTF, diagnostics or Waiting room
  mutate(discharge_new = case_when(next_location %in% c("DIAGNOSTICS", "OTF", "WAITING ROOM") ~ next_dttm,
                                                              TRUE ~ discharge)) %>% 
  mutate(duration_row_new = difftime(discharge_new, admission, units = "hours"))   

# Merge with csn details
ED_bed_moves_adj <- ED_bed_moves_adj %>% 
  left_join(ED_csn_detail %>% select(csn, ED_last_status, seen4hrs))

# save data for future loading 
outFile = paste0("EDcrowding/flow-mapping/data-raw/ED_bed_moves_adj_JanFeb_",today(),".rda")
save(ED_bed_moves_adj, file = outFile)




# Create node summaries
# ====================

# Final calculation of node durations 
node_duration_adj <- ED_bed_moves_adj %>% 
  mutate(date = date(admission)) %>% 
  group_by(date, room4) %>% 
  summarise(daily_num_pat = n(),
            daily_duration_mean = mean(as.numeric(duration_row_new, units = "hours")), #this creates daily mean
            daily_duration_sd = sd(as.numeric(duration_row_new, units = "hours"))) #this creates daily SD



# Node durations with breach info 
node_duration_adj_seen4hrs <- ED_bed_moves_adj %>% 
  filter(!room4  %in% c("DIAGNOSTICS", "OTF", "WAITING ROOM"), !is.na(room4)) %>% 
  mutate(date = date(admission)) %>% 
  group_by(date, seen4hrs, room4) %>% 
  summarise(daily_num_pat = n(),
            daily_duration_mean = mean(as.numeric(duration_row_new, units = "hours")), #this creates daily mean
            daily_duration_sd = sd(as.numeric(duration_row_new, units = "hours"))) 


# Save node summaries for Python

node_duration_adj_summ <- node_duration_adj %>% 
  filter(!room4  %in% c("DIAGNOSTICS", "OTF", "WAITING ROOM"), !is.na(room4)) %>% 
  group_by(room4) %>% 
  summarise(num_pat_mean = mean(daily_num_pat),
            num_pat_sd = sd(daily_num_pat),
            duration_mean = mean(daily_duration_mean),
            duration_sd = sd(daily_duration_mean)) %>% 
  # add mean and SD for breach only
  left_join(
    node_duration_adj_seen4hrs %>% 
      filter(!room4  %in% c("DIAGNOSTICS", "OTF", "WAITING ROOM"), !is.na(room4), 
             seen4hrs == 'Breach') %>% 
      group_by(room4) %>% 
      summarise(num_pat_mean_breach = mean(daily_num_pat),
                num_pat_sd_beach = sd(daily_num_pat),
                duration_mean_breach = mean(daily_duration_mean),
                duration_sd_breach = sd(daily_duration_mean))
  ) %>% 
  # add mean and SD for not breach (seen 4 hours) only
  left_join(
    node_duration_adj_seen4hrs %>% 
      filter(!room4  %in% c("DIAGNOSTICS", "OTF", "WAITING ROOM"), !is.na(room4), 
             seen4hrs == 'Seen in 4 hours') %>% 
      group_by(room4) %>% 
      summarise(num_pat_mean_seen4hrs = mean(daily_num_pat),
                num_pat_sd_seen4hrs = sd(daily_num_pat),
                duration_mean_seen4hrs = mean(daily_duration_mean),
                duration_sd_seen4hrs = sd(daily_duration_mean))
  )


outFile = paste0("EDcrowding/flow-mapping/data-output/node_duration_adj_summ_JanFeb_",today(),".csv")
write.csv2(node_duration_adj_summ, file = outFile, row.names = FALSE)

# Create charts
# =============

# chart of mean for each location by day (through Jan and Feb)

node_duration_adj %>% 
  filter(!room4  %in% c("DIAGNOSTICS", "OTF", "WAITING ROOM"), !is.na(room4)) %>% 
  ggplot(aes(x = date, y = daily_duration_mean)) + geom_bar(stat = "identity") +
  facet_grid(room4 ~.) +
  labs(title = "Mean hours spent in location",
       subtitle = "Source: Star",
       x = "",
       y = "Mean duration (hours)"
  ) +  
  theme_classic()  

# chart of mean over the whole of Jan and Feb

node_duration_adj %>% 
  filter(!room4  %in% c("DIAGNOSTICS", "OTF", "WAITING ROOM"), !is.na(room4)) %>% 
  group_by(room4) %>% 
  summarise(duration_mean = mean(daily_duration_mean)) %>% 
  ggplot(aes(x = room4, y = duration_mean)) + geom_bar(stat = "identity")


# chart of mean for each location by day (through Jan and Feb) - with breach information

node_duration_adj_seen4hrs %>% 
  filter(!room4  %in% c("DIAGNOSTICS", "OTF", "WAITING ROOM"), !is.na(room4),
         !is.na(seen4hrs)) %>% 
  group_by(room4) %>%   
  ggplot(aes(x = date, y = daily_duration_mean, fill = seen4hrs)) + geom_bar(stat = "identity") +
  facet_grid(room4 ~.) +
  labs(title = "Mean hours spent in location",
       subtitle = "Source: Star",
       x = "",
       y = "Mean duration (hours)",
       fill = "Breach status:"
  ) +  
  theme_classic() +
  theme(legend.position="bottom") 
  


# chart of mean over the whole of Jan and Feb - with breach information

node_duration_adj_seen4hrs %>% 
  group_by(seen4hrs) %>% 
  summarise(duration_mean = mean(daily_duration_mean)) %>% 
  ggplot(aes(x = room4, y = duration_mean)) + geom_bar(stat = "identity")


