# About this script
# ================

# Loads ED bed move data generated by get-ED-data-from-Star.R
# Creates details about each encounter including last ED location
# and whether admitted or discharged from ED

# Load libraries
# ==============

library(DBI)
library(dplyr)
library(tidyverse)
library(lubridate)



# Define functions
# ================



# Load data
# =========

# ED bed move data generated by get-ED-data-from-Star.R
inFile = paste0("EDcrowding/flow-mapping/data-raw/ED_bed_moves_","2020-07-01",".rda")
load(inFile)

# CSN data generated by get-ED-data-from-Star.R - all data up to end June
load("~/EDcrowding/flow-mapping/data-raw/ED_csn_summ_2020-07-02.rda")


# load edge list - note this version only Jan/Feb
inFile = paste0("EDcrowding/flow-mapping/data-raw/ED_edge_list_exc_ped_full_","2020-07-03",".rda")
load(inFile)

# Process data
# ============

# create a second file of ED csns with more detail
ED_csn_detail <- ED_csn_summ %>% 
 # filter(arrival_dttm < "2020-03-01") %>% 
  select(-covid) %>% 
  left_join(edgedf %>% filter(to == "Discharged") %>% select(-to),
            by = c("mrn", "csn", "discharge_dttm" = "dttm")) %>%  #need to think about people who are not discharged yet
  rename(discharge_from_loc = from)

# the above doesn't capture the last ED location for admitted patients
ED_csn_detail <- ED_csn_detail %>% 
  left_join(edgedf %>% filter(to == "Admitted") %>% select(-to, dttm),
            by = c("mrn", "csn")) %>%  #need to think about people who are not discharged yet
  rename(admitted_from_loc = from)

# consolidate last ED location
ED_csn_detail <- ED_csn_detail %>% 
  mutate(ED_last_loc = ifelse(is.na(admitted_from_loc), discharge_from_loc, admitted_from_loc))

# create admitted/discharged
ED_csn_detail <- ED_csn_detail %>% 
  mutate(ED_last_status = ifelse(is.na(admitted_from_loc), "Discharged", "Admitted"))

# write to file
outFile <- paste0("EDcrowding/flow-mapping/data-raw/ED_csn_detail_full_",today(),".rda")
save(ED_csn_detail, file = outFile)
