# About this script
# ================

# Loads ED bed move data generated by get-ED-data-from-Star.R
# Creates details about each encounter

# Load libraries
# ==============

library(DBI)
library(dplyr)
library(tidyverse)
library(lubridate)



# Define functions
# ================



# Load data
# =========

# ED bed move data generated by get-ED-data-from-Star.R
inFile = paste0("EDcrowding/flow-mapping/data-raw/ED_bed_moves_","2020-07-01",".rda")
load(inFile)

# CSN data generated by get-ED-data-from-Star.R - all data up to end June
load("~/EDcrowding/flow-mapping/data-raw/ED_csn_summ_2020-07-02.rda")


# load edge list - note this version only Jan/Feb
inFile = paste0("EDcrowding/flow-mapping/data-raw/ED_edge_list_exc_ped","2020-07-01",".rda")
load(inFile)

# Process data
# ============

# create a second file of ED csns with more detail
ED_csn_detail <- ED_csn_summ %>% filter(arrival_dttm < "2020-03-01") %>% select(-covid) %>% 
  left_join(edgedf %>% filter(to == "Discharge") %>% select(-to),
            by = c("mrn", "csn", "discharge_dttm" = "dttm")) %>%  #need to think about people who are not discharged yet
  rename(ED_last_location = from)
