# About this script
# ================

# Loads ED bed flow data from get-ED-data-from-Star.R
# Creates charts

# Load libraries
# ==============

library(DBI)
library(dplyr)
library(tidyverse)
library(lubridate)

# Load data
# =========

# ED bed move data generated by "get-ED-data-from-Star.R"
inFile = paste0("EDcrowding/flow-mapping/data-raw/ED_bed_moves_","2020-07-22",".rda")
load(inFile)

# Detail for ED CSNs generated by "get-ED-data-from-Star.R"
load("~/EDcrowding/flow-mapping/data-raw/ED_csn_summ_2020-07-23.rda")

# Create node list
# ================

# Calculate node durations

node_stats <- ED_bed_moves %>% 
  filter(ED_row ==  1,
         !is.na(room4_new)) %>% 
  mutate(date = date(admission)) %>% 
  group_by(date, room4_new) %>% 
  summarise(daily_duration_mean = mean(as.numeric(duration_row, units = "hours")), #this creates daily mean
            daily_duration_sd = sd(as.numeric(duration_row, units = "hours"))) 

# chart of mean for each location by day 

node_stats %>% 
  ggplot(aes(x = date, y = daily_duration_mean)) + geom_bar(stat = "identity") +
  facet_grid(room4_new ~.) 

# chart of mean over the whole of Jan and Feb

node_stats %>% 
  group_by(room4) %>% 
  summarise(duration_mean = mean(daily_duration_mean),
            duration_sd = sd(daily_duration_mean)) %>% # calculating the standard deviation of the mean
  ggplot(aes(x = room4, y = duration_mean)) + geom_bar(stat = "identity")


# Create node summaries
# ====================

# Final calculation of node durations for ED first
node_stats <- ED_bed_moves %>% 
  filter(arrival_dttm < "2020-03-01") %>% 
  filter(ED_row ==  1,
         !is.na(room4_new)) %>% 
  mutate(date = date(admission)) %>% 
  group_by(date, room4_new) %>% 
  summarise(daily_num_pat = n(),
            daily_duration_mean = mean(as.numeric(duration_row_new, units = "hours")), #this creates daily mean
            daily_duration_sd = sd(as.numeric(duration_row_new, units = "hours"))) #this creates daily SD

# Add Admitted and Discharged as nodes
node_stats <- node_stats %>% dplyr::union(
  ED_bed_moves %>% 
    filter(arrival_dttm < "2020-03-01") %>% 
    left_join(ED_csn_summ %>% select(csn, ED_last_status)) %>% 
    mutate(date = date(admission)) %>% 
    group_by(date, ED_last_status) %>% 
    summarise(daily_num_pat = n(),
              daily_duration_mean = mean(as.numeric(duration_row_new, units = "hours")), #this creates daily mean
              daily_duration_sd = sd(as.numeric(duration_row_new, units = "hours"))) %>% #this creates daily SD
    rename(room4_new = ED_last_status) 
)

# Node durations with breach info 
node_stats_seen4hrs <- ED_bed_moves %>% 
  filter(arrival_dttm < "2020-03-01") %>% 
  filter(ED_row ==  1,
         !is.na(room4_new)) %>% 
  left_join(ED_csn_summ %>% select(csn, seen4hrs)) %>% 
  mutate(date = date(admission)) %>% 
  group_by(date, seen4hrs, room4_new) %>% 
  summarise(daily_num_pat = n(),
            daily_duration_mean = mean(as.numeric(duration_row_new, units = "hours")), #this creates daily mean
            daily_duration_sd = sd(as.numeric(duration_row_new, units = "hours"))) 


# Add Admitted and Discharged as nodes
node_stats_seen4hrs <- node_stats_seen4hrs %>% dplyr::union(
  ED_bed_moves %>% 
    filter(arrival_dttm < "2020-03-01") %>% 
    left_join(ED_csn_summ %>% select(csn, ED_last_status, seen4hrs)) %>% 
    mutate(date = date(admission)) %>% 
    group_by(date, seen4hrs, ED_last_status) %>% 
    summarise(daily_num_pat = n(),
              daily_duration_mean = mean(as.numeric(duration_row_new, units = "hours")), #this creates daily mean
              daily_duration_sd = sd(as.numeric(duration_row_new, units = "hours"))) %>% #this creates daily SD
    rename(room4_new = ED_last_status) 
)

# Save node summaries for Python

node_stats_summ <- node_stats %>% 
  group_by(room4_new) %>% 
  summarise(num_pat_mean = mean(daily_num_pat),
            num_pat_sd = sd(daily_num_pat),
            duration_mean = mean(daily_duration_mean),
            duration_sd = sd(daily_duration_mean)) %>% 
  # add mean and SD for breach only
  left_join(
    node_stats_seen4hrs %>% 
      filter(seen4hrs == 'Breach') %>% 
      group_by(room4_new) %>% 
      summarise(num_pat_mean_breach = mean(daily_num_pat),
                num_pat_sd_beach = sd(daily_num_pat),
                duration_mean_breach = mean(daily_duration_mean),
                duration_sd_breach = sd(daily_duration_mean))
  ) %>% 
  # add mean and SD for not breach (seen 4 hours) only
  left_join(
    node_stats_seen4hrs %>% 
      filter(seen4hrs == 'Seen in 4 hours') %>% 
      group_by(room4_new) %>% 
      summarise(num_pat_mean_seen4hrs = mean(daily_num_pat),
                num_pat_sd_seen4hrs = sd(daily_num_pat),
                duration_mean_seen4hrs = mean(daily_duration_mean),
                duration_sd_seen4hrs = sd(daily_duration_mean))
  )


outFile = paste0("EDcrowding/flow-mapping/data-output/node_stats_JanFeb_",today(),".csv")
write.csv2(node_stats_summ, file = outFile, row.names = FALSE)

# Create charts
# =============

# chart of mean for each location by day (through Jan and Feb)
# note - these charts still use room4 - will need to revisit this

node_stats %>% 
  filter(!room4  %in% c("DIAGNOSTICS", "OTF", "WAITING ROOM"), !is.na(room4)) %>% 
  ggplot(aes(x = date, y = daily_duration_mean)) + geom_bar(stat = "identity") +
  facet_grid(room4 ~.) +
  labs(title = "Mean hours spent in location",
       subtitle = "Source: Star",
       x = "",
       y = "Mean duration (hours)"
  ) +  
  theme_classic()  

# chart of mean over the whole of Jan and Feb

node_stats %>% 
  filter(!room4  %in% c("DIAGNOSTICS", "OTF", "WAITING ROOM"), !is.na(room4)) %>% 
  group_by(room4) %>% 
  summarise(duration_mean = mean(daily_duration_mean)) %>% 
  ggplot(aes(x = room4, y = duration_mean)) + geom_bar(stat = "identity")


# chart of mean for each location by day (through Jan and Feb) - with breach information

node_stats_seen4hrs %>% 
  filter(!room4  %in% c("DIAGNOSTICS", "OTF", "WAITING ROOM"), !is.na(room4),
         !is.na(seen4hrs)) %>% 
  group_by(room4) %>%   
  ggplot(aes(x = date, y = daily_duration_mean, fill = seen4hrs)) + geom_bar(stat = "identity") +
  facet_grid(room4 ~.) +
  labs(title = "Mean hours spent in location",
       subtitle = "Source: Star",
       x = "",
       y = "Mean duration (hours)",
       fill = "Breach status:"
  ) +  
  theme_classic() +
  theme(legend.position="bottom") 
  


# chart of mean over the whole of Jan and Feb - with breach information

node_stats_seen4hrs %>% 
  group_by(seen4hrs) %>% 
  summarise(duration_mean = mean(daily_duration_mean)) %>% 
  ggplot(aes(x = room4, y = duration_mean)) + geom_bar(stat = "identity")


