# About this script
# ================

# Loads ED bed flow data from get-ED-data-from-Star.R
# Creates charts

# Load libraries
# ==============

library(DBI)
library(dplyr)
library(tidyverse)
library(lubridate)

# Load data
# =========

# ED bed move data generated by "get-ED-data-from-Star.R"
inFile = paste0("EDcrowding/flow-mapping/data-raw/ED_bed_moves_","2020-07-09",".rda")
load(inFile)

# Summary for ED CSNs generated by "get-ED-data-from-Star.R"
# Note - need to load summary not detail data
load("~/EDcrowding/flow-mapping/data-raw/ED_csn_summ_2020-07-09.rda")


# Create node list
# ================

# work out csns to ignore if involve pediatrics 
pediatric_csn <- ED_bed_moves %>% group_by(mrn, csn, arrival_dttm) %>% 
  summarise(tot = sum(pediatric_row)) %>% 
  filter(tot > 0) %>% 
  select(mrn, csn) %>% distinct() # 4723

# some csns have rows where the discharge time is earlier than the admission time
odd_csn <- ED_bed_moves %>% filter(discharge < admission) %>% select(csn)
# to see the number of csns removed: 
odd_csn %>% select(csn) %>% n_distinct() #111

# some ED rows have no information about which room someone was in
no_room_csn <-  ED_bed_moves %>% filter(is.na(room4)) %>% select(csn)
# to see the number of csns removed:
no_room_csn %>% select(csn) %>% n_distinct() #8

# To calculate node duration

node_duration <- ED_bed_moves %>% 
  filter(
    ED_row ==  1,
    date(arrival_dttm) < "2020-03-01",
    date(arrival_dttm) >= "2020-01-01",
    !csn %in% pediatric_csn$csn,
    !csn %in% no_room_csn,    
    !csn %in% odd_csn$csn) %>% 
  mutate(date = date(admission)) %>% 
  group_by(date, room4) %>% 
  summarise(daily_duration_mean = mean(as.numeric(duration_row, units = "hours")), #this creates daily mean
            daily_duration_sd = sd(as.numeric(duration_row, units = "hours"))) 


# chart of mean over the whole of Jan and Feb
node_duration %>% 
  group_by(room4) %>% 
  summarise(duration_mean = mean(daily_duration_mean),
            duration_sd = sd(daily_duration_mean)) %>% # calculating the standard deviation of the mean
  ggplot(aes(x = room4, y = duration_mean)) + geom_bar(stat = "identity")

node_duration %>% 
  ggplot(aes(x = date, y = daily_duration_mean)) + geom_bar(stat = "identity") +
  facet_grid(room4 ~.)


## making charts of the above, I realised that OTF is treated as a separate node. Therefore if I'm interested in node duration, I need to extend the previous node time. 

# make a plot of OTF to have a reference for which days had long OTF time
node_duration %>% 
  filter(room4 == "OTF") %>% 
  ggplot(aes(x = date, y = daily_duration_mean)) + geom_bar(stat = "identity") + theme_classic()

# doing this, realised that some very long ED_durations

ED_bed_moves %>% filter(ED_row == 1) %>%  
  
  ggplot(aes(x=1, y = as.numeric(ED_duration, units = "days"))) + 
  geom_boxplot() +
  facet_grid(room4 == "OTF"~.)


# continuing to investigate

long_ED_csn <-  ED_bed_moves %>% filter(as.numeric(ED_duration, units = "days") > 1) %>% select(csn)  # 890
b <- ED_bed_moves %>% 
  filter(csn %in% long_ED_csn$csn) %>% 
  mutate(ED_duration = as.numeric(ED_duration, units = "days"), 
         duration = as.numeric(duration, units = "days"),
         duration_row = as.numeric(duration_row, units = "days")) %>% 
  arrange(desc(ED_duration)) %>% 
  select(duration, ED_duration, duration_row, ED_row, admission, discharge, everything())
b

# looking at b I realise there are some csns that scan across visits eg:

ED_bed_moves %>% filter(csn == "1017123240")

# this code identifies visits where someone goes to ED from another location - quite satisfying to write

d <- ED_bed_moves %>% 
  group_by(csn) %>% 
  select(csn, ED_row, arrival_row) %>% 
  mutate(check = case_when(ED_row == 1 & !arrival_row & lag(ED_row) == 0 ~ "B",
                          TRUE ~ "A"))
elsewhere_to_ED_csn <- d %>% filter(check == "B") %>% select(csn)
a <- ED_bed_moves %>% filter(csn %in% elsewhere_to_ED_csn$csn) %>% select(arrival_row, csn, ED_row, hl7_location, ED_duration, duration, everything())

# the problematic ones are those where the first arrival was ED and then they go back there
mult_ED_csn <- ED_bed_moves %>% filter(csn %in% elsewhere_to_ED_csn$csn, arrival_row, ED_row == 1) %>% select(csn)
b <- ED_bed_moves %>% filter(csn %in% mult_ED_csn$csn) %>% select(arrival_row, csn, ED_row, hl7_location, ED_duration, duration, everything())

# for now I will delete these from analysis, but ultimately should accommodate them in my edge list processing etc. 

ED_bed_moves %>% filter(ED_row == 1,
                        !csn %in% mult_ED_csn$csn) %>%  
  
  ggplot(aes(x=1, y = as.numeric(ED_duration, units = "days"))) + 
  geom_boxplot() +
  facet_grid(room4 == "OTF"~.)

# plots still showing many long visits

# Continuing to look at long CSNs

long_ED_csn <-  ED_bed_moves %>% filter(!csn %in% mult_ED_csn$csn,
                                        as.numeric(ED_duration, units = "days") > 1) %>% select(csn) %>% distinct()

# still 112 csns with more than one day

b <- ED_bed_moves %>% 
  filter(csn %in% long_ED_csn$csn) %>% 
  select(duration, ED_duration, duration_row, ED_row, admission, discharge, everything())
b

b %>% group_by(csn) %>% filter(admission == max(admission)) %>% select(room4) %>% group_by(room4) %>% summarise(tot = n()) %>% arrange(desc(tot))


# looking at where people were in their last row
stuck_in_otf_csn <- b %>% group_by(csn) %>% filter(admission == max(admission), room4 == "OTF") %>% select(csn)
c <- b %>% filter(csn %in% stuck_in_otf$csn)
d <- b %>% filter(!csn %in% stuck_in_otf$csn)

# Derr ! realised that I still have a lot of people who moved to ED from elsewhere so I still need to remove these as well


ED_bed_moves %>% filter(ED_row == 1,
                        !csn %in% elsewhere_to_ED_csn$csn) %>%  
  
  ggplot(aes(x=1, y = as.numeric(ED_duration, units = "days"))) + 
  geom_boxplot() +
  facet_grid(room4 == "OTF"~.)

# Even now, many long visits

long_ED_csn <-  ED_bed_moves %>% filter(!csn %in% elsewhere_to_ED_csn$csn,
                                        as.numeric(ED_duration, units = "days") > 1) %>% select(csn) %>% distinct()

# still 92 csns with more than one day - so repeating the code from above to find out where they get stuck

b <- ED_bed_moves %>% 
  filter(csn %in% long_ED_csn$csn) %>% 
  select(duration, ED_duration, duration_row, ED_row, admission, discharge, everything())
b %>% group_by(csn) %>% filter(admission == max(admission)) %>% select(room4) %>% group_by(room4) %>% summarise(tot = n()) %>% arrange(desc(tot))
# lots in OTF and TAF

stuck_in_otf_taf_csn <- b %>% group_by(csn) %>% filter(admission == max(admission), room4 %in% c("OTF", "TAF")) %>% select(csn)
c <- b %>% filter(csn %in% stuck_in_otf_taf_csn$csn)
d <- b %>% filter(!csn %in% stuck_in_otf_taf_csn$csn)

# Two others got stuck in OTF but it's not the last ED row so I didn't pick them up above
# Rewriting the code above; interesting that you have to do two separate filters - picked up 5 more this way
stuck_in_otf_taf_csn <- b %>% group_by(csn) %>% filter(ED_row == 1) %>% filter(admission == max(admission), room4 %in% c("OTF", "TAF")) %>% select(csn)
d <- b %>% filter(!csn %in% stuck_in_otf_taf_csn$csn)

# One is genuinely weird - spent 2 months in ED but only one row
ED_bed_moves %>% filter(csn == "1018734672")
# Others could be genuinely in ED for over a day

f <- d %>% filter(
  !csn %in% stuck_in_otf_taf_csn$csn,
  !csn == "1018734672"
)

# this one spent 163 in OTF and then went elsewhere in ED so I didn't pick them up
ED_bed_moves %>% filter(csn == "1019997966")

f <- d %>% filter(
  !csn %in% stuck_in_otf_taf_csn$csn,
  !csn == "1019997966",  
  !csn == "1018734672"
)

# looking again at the basic ED plot - looks a lot more sensible

ED_bed_moves %>% filter(
    ED_row ==  1,
    date(arrival_dttm) < "2020-03-01",
    date(arrival_dttm) >= "2020-01-01",
    !csn %in% pediatric_csn$csn,
    !csn %in% no_room_csn,    
    !csn %in% odd_csn$csn,
    !csn %in% elsewhere_to_ED_csn$csn,
    !csn %in% mult_ED_csn$csn,
    !csn %in% stuck_in_otf_taf_csn$csn,
    !csn %in% OTF_gt_24_hrs_csn$csn,
    !csn == "1019997966",  
    !csn == "1018734672") %>% 
  
  ggplot(aes(x=1, y = as.numeric(ED_duration, units = "days"))) + 
  geom_boxplot() +
  facet_grid(room4 == "OTF"~.)

# Therefore recalculate node durations

node_duration <- ED_bed_moves %>% 
  filter(
    ED_row ==  1,
    date(arrival_dttm) < "2020-03-01",
    date(arrival_dttm) >= "2020-01-01",
    !csn %in% pediatric_csn$csn,
    !csn %in% no_room_csn,    
    !csn %in% odd_csn$csn,
    !csn %in% elsewhere_to_ED_csn$csn,
    !csn %in% mult_ED_csn$csn,
    !csn %in% stuck_in_otf_taf_csn$csn,
    !csn %in% OTF_gt_24_hrs_csn$csn,
    !csn == "1019997966",  
    !csn == "1018734672") %>% 
  mutate(date = date(admission)) %>% 
  group_by(date, room4) %>% 
  summarise(daily_duration_mean = mean(as.numeric(duration_row, units = "hours")), #this creates daily mean
            daily_duration_sd = sd(as.numeric(duration_row, units = "hours"))) 

node_duration %>% 
  ggplot(aes(x = date, y = daily_duration_mean)) + geom_bar(stat = "identity") +
  facet_grid(room4 ~.)


# chart of mean over the whole of Jan and Feb
node_duration %>% 
  group_by(room4) %>% 
  summarise(duration_mean = mean(daily_duration_mean),
            duration_sd = sd(daily_duration_mean)) %>% # calculating the standard deviation of the mean
  ggplot(aes(x = room4, y = duration_mean)) + geom_bar(stat = "identity")

node_duration %>% 
  ggplot(aes(x = date, y = daily_duration_mean)) + geom_bar(stat = "identity") +
  facet_grid(room4 ~.)


z <- ED_bed_moves %>% 
  filter(
    ED_row ==  1,
    date(arrival_dttm) < "2020-03-01",
    date(arrival_dttm) >= "2020-01-01",
    !csn %in% pediatric_csn$csn,
    !csn %in% no_room_csn,    
    !csn %in% odd_csn$csn,
    !csn %in% elsewhere_to_ED_csn$csn,
    !csn %in% mult_ED_csn$csn,
    !csn %in% stuck_in_otf_taf_csn$csn,
    !csn %in% OTF_gt_24_hrs_csn$csn,
    !csn == "1019997966",  
    !csn == "1018734672")

y <- z %>% group_by(csn) %>% mutate(next_location = lead(room4),
                                    next_dttm = lead(discharge))
y <- y %>% mutate(discharge_new = case_when(next_location %in% c("DIAGNOSTICS", "OTF", "WAITING ROOM") ~ next_dttm,
                                                              TRUE ~ discharge))
                               