# About this script
# ================

# Loads ED bed move data generated by get-ED-data-from-Star.R
# Creates an edge list, which contains one row per bed move per patient
# and has a timestamp. 
#
# Note that this does not do any grouping of nodes
# that is done in the script called 'Get-ED-data-from-Star.R'
# Locations in the hospital are assumed to be grouped into nodes of interest. 

# Load libraries
# ==============

library(DBI)
library(dplyr)
library(tidyverse)
library(lubridate)


# Define functions
# ================

# define level of granularity for node
# if in ED use room, else node set to Admission for all wards

get_node <- function(dept, room) {
  if (dept == "Still in ED") {
    node <- room
  }
  else {
    node <- dept
  }
}

# for a single encounter, this function generates an edge list of 
# moves between locations, with a timestamp
# locations are provided to it in a tibble called sites
# sites needs 5 attributes: mrn, csn, location, time of admission to location, 
# and time of discharge from location

get_edgelist <- function(sites) {
  
  edgelist <- tribble(
    ~mrn,
    ~csn,
    ~from,
    ~to,
    ~dttm)
  
  from_node = get_node(as.character(sites$dept3[1]), as.character(sites$room4_new[1]))
  for (j in 1:nrow(sites)) {
    if (j != nrow(sites)) {
      to_node <- get_node(as.character(sites$dept3[j+1]), as.character(sites$room4_new[j+1]))
      
      # in any of the following cases, ignore the to node and move to next row
      if (!(to_node %in% c("OTF", "DIAGNOSTICS", "WAITING ROOM")) && !is.na(to_node)) {
        if (from_node != to_node) {
          
          edgelist <- edgelist %>% add_row(tibble_row(
            mrn = sites$mrn[j],
            csn = sites$csn[j],
            from = from_node,
            to = to_node,
            dttm = sites$discharge_new[j]
          ))
        }
        from_node <- to_node
      }
    }
    else {
      if (!(to_node %in% c("OTF", "DIAGNOSTICS", "WAITING ROOM")) && !is.na(to_node)) {
        
        edgelist <- edgelist %>% add_row(tibble_row(
          mrn = sites$mrn[j],
          csn = sites$csn[j],
          from = to_node,
          to = "Discharged",
          dttm = sites$discharge_dttm[j]
        ))
      }
      else {
        
        # added new code here - need to check it works 
        
        edgelist <- edgelist %>% add_row(tibble_row(
          mrn = sites$mrn[j],
          csn = sites$csn[j],
          from = from_node,
          to = "Discharged",
          dttm = sites$discharge_dttm[j]
        ))
      }
    }
  }
  return(edgelist)
}


# for  group of encounters, this function generates an edge list of 
# all moves between locations, with a timestamp for each move
# locations are provided to it in a tibble called visits
# visits needs 5 attributes: mrn, csn, location, time of admission to location, 
# time of discharge from location


get_care_site_flows <- function(visits) {

  # filter only those visits with more than one room move
  visits_gt1 <- visits %>% 
    group_by(mrn, csn) %>% 
    summarise("num_visit_details" = n(), "earliest_visit_ts" = min(admission)) %>% 
    filter(num_visit_details > 1)
  
  # then create edge list for all visits
  
  edgedf <- tribble(
    ~mrn,
    ~csn,
    ~from,
    ~to,
    ~dttm)
  
  for (i in (1:nrow(visits_gt1))) {
    
    if (i%%100 == 0) {
      print(paste("Processed",i,"visits"))
    }
    visit_csn = visits_gt1$csn[i]
    num_visits = visits_gt1$num_visit_details[i]
    
    #get all visit detail records for this visit occurence
    sites <- visits %>% filter(csn == visit_csn) %>% arrange(admission)
    
    # create edgelist if the visit involved change of site
    edgelist <- get_edgelist(sites)
    if (nrow(edgelist) > 0) {
      edgedf <- edgedf %>% add_row(edgelist)
    }
  }
  return(edgedf)
}





# Load data
# =========

# ED bed move data generated by "get-ED-data-from-Star.R"
inFile = paste0("EDcrowding/flow-mapping/data-raw/ED_bed_moves_","2020-07-22",".rda")
load(inFile)

# Summary for ED CSNs generated by "get-ED-data-from-Star.R"
# Note - need to load summary not detail data
load("~/EDcrowding/flow-mapping/data-raw/ED_csn_summ_2020-07-09.rda")


# Create edge list
# ================

# create edge list which contains one row per bed move per patient with a time stamp
# note this is currently using room4_new, which is the grouped version of room and
# that it subsumes OTF into the previous node 
edgedf <- get_care_site_flows(ED_bed_moves %>% 
#                                filter(arrival_dttm < "2020-03-01") %>% 
                                select(mrn, csn, dept2, dept3, room4_new, admission, arrival_dttm, discharge_new, discharge_dttm) )

# save edge list for future use
outFile = paste0("EDcrowding/flow-mapping/data-raw/ED_edgelist_full_",today(),".rda")
save(edgedf, file = outFile)
rm(outFile)

# OR load edge list if already saved



get_care_site_flows(ED_bed_moves %>% 
                      filter(csn == "1020164549",
                        #                                  arrival_dttm < "2020-03-01", 
                        !csn %in% pediatric_csn$csn,
                        !csn %in% odd_csn$csn) %>% 
                      select(mrn, csn, dept2, dept3, room4, admission, arrival_dttm, discharge, discharge_dttm))

