# About this script
# ================

# Loads ED bed move data generated by get-ED-data-from-Star.R
# Creates details about each encounter including last ED location
# and whether admitted or discharged from ED

# Load libraries
# ==============

library(DBI)
library(dplyr)
library(tidyverse)
library(lubridate)



# Define functions
# ================



# Load data
# =========

# ED bed move data generated by get-ED-data-from-Star.R
inFile = paste0("EDcrowding/flow-mapping/data-raw/ED_bed_moves_","2020-07-xx",".rda")
load(inFile)

# CSN data generated by get-ED-data-from-Star.R - all data up to end June
load("~/EDcrowding/flow-mapping/data-raw/ED_csn_summ_2020-07-xx.rda")


# load edge list 
load("~/EDcrowding/flow-mapping/data-raw/ED_edgelist_full_grouped_2020-07-xx.rda")
load(inFile)

# Process data
# ============

# work out csns to ignore if involve pediatrics 
pediatric_csn <- ED_bed_moves %>% group_by(mrn, csn, arrival_dttm) %>% 
  summarise(tot = sum(pediatric_row)) %>% 
  filter(tot > 0) %>% 
  select(mrn, csn) %>% distinct() #4723

# work out if csn has a row where discharge is before admission
odd_csn <- ED_bed_moves %>% filter(discharge < admission) %>% select(csn)
# to see the number of csns removed: 
odd_csn %>% select(csn) %>% n_distinct() #111

# some ED rows have no information about which room someone was in
no_room_csn <-  ED_bed_moves %>% filter(is.na(room4)) %>% select(csn)
# to see the number of csns removed:
no_room_csn %>% select(csn) %>% n_distinct() #8

# create a second file of ED csns with more detail
ED_csn_detail <- ED_csn_summ %>% 
  filter(!csn %in% pediatric_csn$csn,
         !csn %in% odd_csn$csn,
         !csn %in% no_room_csn$csn) %>% 
  left_join(edgedf %>% filter(to == "Discharged") %>% select(-to),
            by = c("mrn", "csn", "discharge_dttm" = "dttm")) %>%  #need to think about people who are not discharged yet
  rename(discharge_from_loc = from)

# add the last ED location for admitted patients
ED_csn_detail <- ED_csn_detail %>% 
  left_join(edgedf %>% filter(to == "Admitted") %>% select(-to, -dttm),
            by = c("mrn", "csn")) %>%  #need to think about people who are not discharged yet
  rename(admitted_from_loc = from)

# consolidate last ED location
ED_csn_detail <- ED_csn_detail %>% 
  mutate(ED_last_loc = ifelse(is.na(admitted_from_loc), discharge_from_loc, admitted_from_loc))

# create admitted/discharged
ED_csn_detail <- ED_csn_detail %>% 
  mutate(ED_last_status = ifelse(is.na(admitted_from_loc), "Discharged", "Admitted"))

# create breach detail
ED_csn_detail <- ED_csn_detail %>% 
  mutate(seen4hrs = ifelse(ED_duration < hours(4), "Seen in 4 hours", "Breach"))



# Some rows have NA in ED_last_loc 
# Some have only one ED row so no moves of interest - to see these
ED_csn_detail %>% filter(is.na(ED_last_loc), num_ED_rows == 1) %>% summarise(n_distinct(csn))
ED_csn_detail %>% filter(is.na(ED_last_loc), num_ED_rows > 1) 
# Currently this leaves one row with inconsisent information
# ED_bed_moves has one row, but ED_csn_detail records 2 rows 
# ED_bed_moves %>% filter(csn == "1018734672")

# Therefore remove rows with NA in ED_last_loc 
ED_csn_detail <- ED_csn_detail %>% filter(!is.na(ED_last_loc))





# write to file
outFile <- paste0("EDcrowding/flow-mapping/data-raw/ED_csn_detail_full_",today(),".rda")
save(ED_csn_detail, file = outFile)
