# About this script
# ================

# Loads ED bed move data generated by get-ED-data-from-Star.R
# Creates an edge list, which contains one row per bed move per patient
# and has a timestamp. 
#
# Note that this does not do any grouping of nodes
# that is done in the script called 'Get-ED-data-from-Star.R'
#
# An additional node is created in two situations
# - A flowsheet measurement is taken prior to the first arrival row 
# - A flowsheet measurement is taken while the person is in a location of "Arrived"

# Load libraries
# ==============

library(dplyr)
library(tidyverse)
library(lubridate)


# Define functions
# ================

# define level of granularity for node
# if in ED use room, else node set to Admission for all wards
# note - this function should catch all rows where OTF is the last row
# as these have been set to Still in ED

get_node <- function(dept, room) {
  if (dept == "Still in ED") {
    node <- room
  }
  else {
    node <- dept
  }
}


# Load data
# =========

file_label <- "JanFeb_"

# ED bed move data generated by "get-ED-data-from-Star.R"
inFile <- paste0("~/EDcrowding/flow-mapping/data-raw/ED_bed_moves_",file_label,"2020-09-01.rda")
load(inFile)

# Summary for ED CSNs generated by "get-ED-data-from-Star.R"
inFile <- paste0("~/EDcrowding/flow-mapping/data-raw/ED_csn_summ_",file_label,"2020-09-01.rda")
load(inFile)

# Load flowsheet data
inFile <- paste0("~/EDcrowding/flow-mapping/data-raw/ED_flowsheets_",file_label,"2020-08-26.rda")
load(inFile)

# Add additional triage row  
# =========================

# alternative version of ED_bed_moves with additional rows
# This section adds a row where person is in status of "Arrived"
# but has had measurements taken
# row admission, discharge and duration are updated accordingly

# Find earliest timestamp in flowdata
ED_bed_moves_with_meas <- ED_bed_moves %>% 
  left_join(ED_flowsheet_raw %>% group_by(csn) %>% 
              summarise(earliest_flowsheet = min(flowsheet_datetime))) %>% 
  select(mrn, csn, arrival_dttm, discharge_dttm, dept3, room7, admission, discharge, 
         ED_row, OTF_row, ED_row_excl_OTF, duration_row, discharge_new, earliest_flowsheet)

extra_rows <- tribble(
  ~mrn, ~csn, ~arrival_dttm, ~discharge_dttm, ~admission , ~discharge, 
  ~dept3,  ~room7,
  ~ED_row, ~OTF_row, ~ED_row_excl_OTF, ~duration_row, 
  ~discharge_new, ~earliest_flowsheet)

# create a new row where the first flowsheet data is earlier than arrival_dttm

ED_bed_moves_with_meas_pre_arrival <- ED_bed_moves_with_meas %>% filter(room7 == "Arrived", arrival_dttm > earliest_flowsheet)

for (i in 1:nrow(ED_bed_moves_with_meas_pre_arrival)) {
  
  row <- ED_bed_moves_with_meas_pre_arrival[i,]
  
  # create new row 
  row$admission <- row$earliest_flowsheet
  row$discharge <- row$arrival_dttm
  row$discharge_new <- row$arrival_dttm  
  row$duration_row <- difftime(row$arrival_dttm, row$earliest_flowsheet, units = "hours")
  row$room7 <- "Meas pre arrival"
  extra_rows <- extra_rows %>% add_row(tibble_row(row))
  
}

rm(ED_bed_moves_with_meas_pre_arrival)

# process rows where triage takes place during Arrival

for (i in 1:nrow(ED_bed_moves_with_meas)) {
  
  if (i%%1000 == 0) {
    print(paste("Processed",i,"rows"))
  }
  
  row <- ED_bed_moves_with_meas[i,]
  
  if(row$room7 == "Arrived" && 
     !is.na(row$earliest_flowsheet) &&
     row$admission > row$earliest_flowsheet) { # find next flowsheet measurement when first one was taken pre arrival
    next_flowsheet <- ED_flowsheet_raw %>%
      filter(csn == row$csn, flowsheet_datetime > row$earliest_flowsheet) 
    
    if (nrow(next_flowsheet) > 0) {
      row$earliest_flowsheet <- min(next_flowsheet$flowsheet_datetime)
    } else {
      row$earliest_flowsheet <- NA_POSIXct_
    }
  }
  
  if(row$room7 == "Arrived" && 
     !is.na(row$earliest_flowsheet) &&
     row$discharge_new > row$earliest_flowsheet) { # Vital signs were taken while person was in Arrived status
    
    # create new row 
    row$admission <- row$earliest_flowsheet
    row$duration_row <- difftime(row$discharge_new, row$earliest_flowsheet, units = "hours") 
    row$room7 <- "Meas post arrival"
    extra_rows <- extra_rows %>% add_row(tibble_row(row))
    
    # update the arrival row duration 
    ED_bed_moves_with_meas$duration_row[i] <- difftime(row$earliest_flowsheet, ED_bed_moves_with_meas$admission[i], units = "hours") 
    ED_bed_moves_with_meas$discharge[i] <- row$earliest_flowsheet
    ED_bed_moves_with_meas$discharge_new[i] <- row$earliest_flowsheet
    
  }
}

ED_bed_moves_with_meas <- ED_bed_moves_with_meas %>% dplyr::union(extra_rows) %>% arrange(mrn, csn, admission)

ED_bed_moves_with_meas <- ED_bed_moves_with_meas %>% 
  group_by(mrn, csn, arrival_dttm, discharge_dttm)%>% 
  mutate(num_ED_rows = sum(ED_row == 1))
  
  
# save ED_bed_moves_with_meas for later use

outFile = paste0("EDcrowding/flow-mapping/data-raw/ED_bed_moves_clean_with_meas_JanFeb_",today(),".rda")
save(ED_bed_moves_with_meas, file = outFile)
rm(outFile)


# Create row numbers if useful
ED_bed_moves_with_meas <- ED_bed_moves_with_meas %>% ungroup() %>%
  mutate(id = row_number()) %>%
  group_by(mrn, csn, arrival_dttm, discharge_dttm)


# Create edge list
# ================

# create edge list which contains one row per bed move per patient with a time stamp
# note this is currently using room7 - see wiki for more on room information

edgedf <- tribble(
  ~mrn,
  ~csn,
  ~from,
  ~to,
  ~dttm)

current_csn = ED_bed_moves_with_meas$csn[1]

for (i in (1:nrow(ED_bed_moves_with_meas))) {
  
  if (i%%1000 == 0) {
    print(paste("Processed",i,"rows"))
  }
  
  from_node <- get_node(as.character(ED_bed_moves_with_meas$dept3[i]), as.character(ED_bed_moves_with_meas$room7[i]))
  
  if(i != nrow(ED_bed_moves_with_meas)) {

    if (ED_bed_moves_with_meas$csn[i+1] == current_csn) {
      
      to_node <- get_node(as.character(ED_bed_moves_with_meas$dept3[i+1]), as.character(ED_bed_moves_with_meas$room7[i+1]))
      
      if (from_node != to_node) {
        edgedf <- edgedf %>% add_row(tibble_row(
          mrn = ED_bed_moves_with_meas$mrn[i],
          csn = ED_bed_moves_with_meas$csn[i],
          from = from_node,
          to = to_node,
          dttm = ED_bed_moves_with_meas$discharge_new[i]
        ))
      }
    }
    else {# write last row for current csn - but skip if only one row
      
      if (ED_bed_moves_with_meas$num_ED_rows[i] > 1) {
        edgedf <- edgedf %>% add_row(tibble_row(
          mrn = ED_bed_moves_with_meas$mrn[i],
          csn = ED_bed_moves_with_meas$csn[i],
          from = to_node,
          to = "Discharged",
          dttm = ED_bed_moves_with_meas$discharge_dttm[i]
        ))
        
      }
      
      current_csn <- ED_bed_moves_with_meas$csn[i+1]
    }
  }
}

# Clean up edges where admission (via OTF) is followed by a return to ED
ED_bed_moves_with_meas %>% filter(csn == "1017779561")

# one way of doing this is skipping rows - but this may mask something useful
# edgedf <- edgedf %>% group_by(mrn, csn) %>% 
#   mutate(
#     skip = case_when(lag(to) == "Admitted" & from == "Admitted" & to != "Discharged" ~ TRUE,
#                      TRUE ~ FALSE),
#     to_new = case_when(to == "Admitted" & lead(from) == "Admitted" & lead(to) != "Discharged" ~ lead(to),
#                        TRUE ~ to),
#     dttm_new = case_when(to == "Admitted" & lead(from) == "Admitted" & lead(to) != "Discharged" ~ lead(dttm),
#                          TRUE ~ dttm),
#   )

# another way is to restore OTF
# which is better done earlier in the process
# have therefore changed get-ED-data-from-Star.R to make sure that dept3 
# is not set to Admitted whenever an OTF row is followed by a return to ED


# save edge list for future use
outFile = paste0("EDcrowding/flow-mapping/data-raw/ED_edgelist_with_meas_",file_label, today(),".rda")
save(edgedf, file = outFile)
rm(outFile)

# OR load edge list if already saved

edgedf %>% filter(csn == "1017542386")

