# Debugging Enoch code

bed_moves_emergency <- as_tibble(read_csv("~/EDcrowding/predict-admission/data-raw/bed_moves_emergency.csv"))

# in the csv file, there should be two rows for this csn (acc DB Forge)
# admission 2020-03-31 09:42:00.000000 discharge 2020-03-31 09:52:20.000000
# admission 2020-03-31 09:52:20.000000 discharge 2020-03-31 11:59:00.000000
# they have been written to the csv file incorrectly

bed_moves_emergency %>% filter(csn == "1019092549") %>% arrange(admission)

bed_moves_raw %>% filter(csn == "1019092549")
# I now know that rows have been deleted based on the code that overwrites everyone in MAJORs etc.


design_matrix <- as_tibble(read_csv("~/EDcrowding/predict-admission/data-raw/design_matrix.csv", 
                                    col_types = cols(
                                      EPIDURAL.INFUSION.RATE = col_double())
                                    # note - need to add more col type specifications
                                    ))
design_matrix %>% filter(csn == "1019092549")

mat_fromfile <- as_tibble(mat_fromfile)


# to compare rows within bed_moves.R generated by Enoch's code versus mine in bed_moves ZK.R
as_tibble(bed_moves1[(bed_moves1$csn==csn[i]),]) %>% arrange(admission)
bed_moves_raw %>% filter(csn == classify_csn[i]) %>% select(-ed_arrival_dttm, -ed_discharge_dttm, -num_ed_rows) %>%  arrange(admission)

adm_zk <- adm_zk %>% distinct()

# to compare Enoch's calculations with mine
check <- adm %>% left_join(adm_zk)
check %>% filter(ADM != admitted)  # 3 false out of 100


bed_moves %>% filter(csn == "1019046018")
bed_moves_raw %>% filter(csn == "1019046018")
